### ISSUE TITLE
discussion: associate intrinsic discriminant numbers with enum values?

### ISSUE THREAD

**Issue by juleskers** [yaa110/rust-httpstatus#1]
As explained here:
https://stackoverflow.com/questions/36928569/enums-with-constant-values-in-rust
An enum value can "_be_" a value.

http status codes are intrinsically associated with their number, so this makes perfect sense to use.

So instead of currently this:

```
pub enum StatusCode {
    /// 100 Continue (RFC 7231)
Continue,
...
```

It would become
```
pub enum StatusCode {
Continue = 100, /// Continue (RFC 7231)
...
```

Is this something that would interest you?

**Comment by yaa110** [comment]
That is the first approach I used to implement this crate. In this situation, the enum variant should be casted to get the associated value, for example:
```rust
let code = StatusCode::Continue as u16;
// use code when you need u16
```

Hoowever, there is no way (except using `From` trait) to convert `u16` to its corresponding enum variant and you would need to match all possible values, i. e.:
```rust
let code_num:u16 = 100
fn get_code(c: StatusCode) {...}
get_code(code_num); // error: expected enum `StatusCode`, found u16
```

As a result, I think the only benefit of using this approach is that we could summarize `as_u16` method of `StatusCode` enum:
```rust
impl StatusCode {
    pub fn as_u16(self) -> u16 {
        self as u16 // rather than matching patterns
    }
}
```

**Comment by juleskers** [comment]
Ah! Good to hear you've already tried this! I'll defer to your experience, and accept whatever you prefer.
A simpler `as_u16` sounds like a fairly minute advantage, I agree.
The only other advantage I can see that the in-memory representation would match the canonical number. This _might_ help people using debuggers, or the (the poor, suffering) colleagues interfacing with C/C++. I'll admit this is not a very pressing need.

A downside that just occurred to me, is that the current implementation, having less than 256 possible values, would probably be a u8 in memory, whereas my suggestion would double it to a u16.
We're talking a single byte here, but tiny stuff like that can add up. It's also a very concrete downside, as opposed to my 
With that, I've convinced myself that the change isn't worthwhile (though I'll happily submit a PR if you so wish). 

Thank you for your time! :-D

**Comment by yaa110** [comment]
Thank you for the contribution. Please feel free to open pull requests to debug or optimize the code.
